velocity_smoother:
  ros__parameters:
    smoothing_frequency: 10.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [0.65, 0.0, 2.5]
    min_velocity: [-0.65, 0.0, -2.5]
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
    max_accel: [0.3, 0.0, 1.5]
    max_decel: [-0.3, 0.0, -1.5]
    odom_topic: "odom"
    odom_duration: 0.1
    use_realtime_priority: false
    enable_stamped_cmd_vel: false